apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s.%s" $.Values.config.namePrefix $.Release.Name | quote }}
  namespace: argocd
  annotations:
    argo.octopus.com/project: {{$.Values.config.project}}
    argo.octopus.com/environment: {{$.Values.config.environment}}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ (printf "%s-%s" $.Values.config.namePrefix $.Release.Name) | quote }}
    server: {{ $.Values.config.destination | quote }}
  project: default
  source:
    path: "ArgoCD/SingleSource"
    repoURL: {{ $.Values.config.source.repoURL | quote }}
    targetRevision: {{ $.Values.config.source.targetRevision | quote }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true