apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nginx-#{Octopus.Environment.Name | toLower}-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nginx-#{Octopus.Environment.Name | toLower}"
  template:
    metadata:
      labels:
        app: "nginx-#{Octopus.Environment.Name | toLower}"
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.29.4
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"