apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s.%s" $.Values.config.namePrefix "multi.source" | quote }}
  namespace: argocd
  annotations:
    argo.octopus.com/project.multi-source-one: {{$.Values.config.project}}
    argo.octopus.com/environment.multi-source-one: {{$.Values.config.environment}}
    argo.octopus.com/project.multi-source-two: {{$.Values.config.project}}
    argo.octopus.com/environment.multi-source-two: {{$.Values.config.environment}}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ (printf "%s-%s" $.Values.config.namePrefix $.Release.Name) | quote }}
    server: {{ $.Values.config.destination | quote }}
  project: default
  sources:
      - name: multi-source-one
        repoURL: {{ $.Values.config.source.repoURL | quote }}
        targetRevision: {{ $.Values.config.source.targetRevision | quote }}
        path: "ArgoCD/MultiSource/SourceOne"
      - name: multi-source-two
        repoURL: {{ $.Values.config.source.repoURL | quote }}
        targetRevision: {{ $.Values.config.source.targetRevision | quote }}
        path: "ArgoCD/MultiSource/SourceTwo"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true